name: Image Compare

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-16.04
    timeout-minutes: 20
    env:
      screenshotter_config_path: ${{ github.workspace }}/tests/screenshotter/config.js
    strategy:
      fail-fast: false
      matrix:
        wordpress_versions: [ 'latest' ]
    name: WordPress ${{ matrix.wordpress_versions }}
    steps:
      - name: Startup MySQL service
        run:  sudo /etc/init.d/mysql start
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          sudo chown -R $USER /usr/local/bin/
          npm i --no-save @elementor/screenshotter
          ./node_modules/@elementor/screenshotter/src/install-dependencies.js --config=${screenshotter_config_path} --debug=true
      - name: Import Templates
        run: |
          ./node_modules/@elementor/screenshotter/src/import-templates.js --config=${screenshotter_config_path} --debug=true
      - name: Build Package & Run Test
        run: |
          ./node_modules/@elementor/screenshotter/src/run-test-screenshotter.js --config=${screenshotter_config_path} --debug=true --deepDebug=true
      - uses: actions/upload-artifact@master
        if: failure()
        with:
          name: backstop-output
          path: /tmp/wordpress/backstop_data
